name: Depliegue Automatico Main Showroom

on:
  push:
    branches: [ main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}

      - name: Execute deploy.sh
        run: |
          ssh -p ${{ secrets.SSH_PORT }} \
              -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "bash -l /home/bel/Showroom/src/deploy.sh 2>&1"
